---
# tasks file for second_role
- name: add several users to a group
  user:
    name: "{{ item }}"
    state: present
    groups: "wheel"
  loop:
    - testuser1
    - testuser2
    - testuser3
    - testuserabc