---
- name: Prepare S3 bucket
  block:
    - name: Define S3 bucket policy
      set_fact:
        s3_bucket_policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicRead",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::httpdlogs-vkb/*"
              }
            ]
          }

    - name: Create S3 bucket
      s3_bucket:
        name: httpdlogs-vkb
        region: us-east-1
        state: present
        policy: "{{ s3_bucket_policy }}"
        public_access:
          block_public_acls: false
          ignore_public_acls: false
          block_public_policy: false
          restrict_public_buckets: false

# By specifying never on the tag of this block, 
# I let this block to run only when explicitely being called
  tags: ['never', 'create']